using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSI.Domain.Entities
{
    public class Saleshead
    {
		public string? transactionno {  get; set; }
		public DateTime? trandate { get; set; }
        public DateTime? trantime { get; set; }
        public string? terminalno { get; set; }
        public string? customer { get; set; }
        public string? encoder { get; set; }
        public string? serviceempno { get; set; }
        public string? serviceemp { get; set; }
        public string? trantype { get; set; }
        public decimal? discamt { get; set; }
        public decimal? discamt_perc { get; set; }
        public decimal? totaldiscount { get; set; }
        public decimal? totalamount { get; set; }
        public decimal? lkey { get; set; }
        public string? pricelevel { get; set; }
        public decimal? senior { get; set; }
        public decimal? lessvat { get; set; }
        public string? termscode { get; set; }
        public string? termsofpayment { get; set; }
        public string? duedate { get; set; }
        public string? locationno { get; set; }
        public string? locationname { get; set; }
        public decimal? giftcheck { get; set; }
		public decimal? claimed { get; set; }
        public string? expirydate { get; set; }
        public string? tableno { get; set; }
        public string? toserve { get; set; }
        public string? docno1 { get; set; }
        public string? docno2 { get; set; }
		public string? docno3 { get; set; }
        public string? sono { get; set; }
        public string? claimtag { get; set; }
        public string? sonumber { get; set; }
        public string? sotrandate { get; set; }
        public string? sobranch { get; set; }
        public string? gcfrom { get; set; }
        public string? gcto { get; set; }
        public string? shiftcode { get; set; }
        public string? vehicle { get; set; }
        public string? cartype { get; set; }
        public string? cashier { get; set; }
        public string? status { get; set; }
        public decimal? noperson { get; set; }
        public decimal? nosenior { get; set; }
        public decimal? servicecharge { get; set; }
        public decimal? totalcost { get; set; }
        public string? saleshour { get; set; }
        public string? deposit { get; set; }
        public decimal? guestcount { get; set; }
        public string? dine { get; set; }
        public string? salescategory { get; set; }
        public string? sc { get; set; }
        public string? roomnumber { get; set; }
        public string? guestname { get; set; }
        public string? custtype { get; set; }
        public string? outlet { get; set; }
        public string? osnumber { get; set; }
        public string? customername { get; set; }
        public string? address { get; set; }
        public string? customertype { get; set; }
        public decimal? previousreading { get; set; }
        public decimal? presentreading { get; set; }
        public string? readingdate { get; set; }
        public decimal? penaltyserved { get; set; }
        public string? padlockdate { get; set; }
        public string? cityname { get; set; }
        public string? zipcode { get; set; }
        public string? province { get; set; }
        public string? country { get; set; }
        public string? dcountry { get; set; }
        public string? dprovince { get; set; }
        public string? dzipcode { get; set; }
        public string? dcityname { get; set; }
        public string? deliveryaddress { get; set; }
        public string? billingaddress { get; set; }
        public string? daddress { get; set; }
        public string? referencenumber { get; set; }
        public string? container { get; set; }
        public string? containerno { get; set; }
        public string? sealno { get; set; }
        public string? invoicecode { get; set; }
        public string? lcno { get; set; }
        public string? pi_no { get; set; }
        public string? formtype { get; set; }
        public string? ccurrency { get; set; }
        public decimal? ccurrencyrate { get; set; }
        public string? glcode { get; set; }
        public string? subgl1 { get; set; }
        public string? subgl2 { get; set; }
        public string? project_code { get; set; }
        public string? departmentname { get; set; }
        public string? projectname { get; set; }
        public string? contactperson { get; set; }
        public string? freightterm { get; set; }
        public string? transactionname { get; set; }
        public decimal? inventory_action { get; set; }
        public string? supplier_code { get; set; }
        public DateTime? deliverydate { get; set; }
        public string? drnumber { get; set; }
        public string? preparedby { get; set; }
        public string? checkedby { get; set; }
        public string? receivedby { get; set; }
        public string? approvedby { get; set; }
        public decimal? discamt_perc2 { get; set; }
        public decimal? discamt_perc2_amount { get; set; }
        public decimal? fired { get; set; }
        public string? location2 { get; set; }
        public decimal? markupperc { get; set; }
        public string? void_reason { get; set; }
        public decimal? vatablesales { get; set; }
        public decimal? nonvatsales { get; set; }
        public decimal? zeroratedsales { get; set; }
        public decimal? vattotal { get; set; }
        public string? voidedby { get; set; }
        public DateTime? voiddate { get; set; }
        public decimal? cash_tender { get; set; }
        public decimal? check_tender { get; set; }
        public decimal? cc_tender { get; set; }
        public decimal? other_tender { get; set; }
        public decimal? change_due { get; set; }
        public int? uploaded { get; set; }
        public int? RECEIVED { get; set; }
        public decimal? noServiceCharge { get; set; }
        public string? dinein_takeout { get; set; }
        public string? loyalty_card_no { get; set; }
	    public string? reservationby { get; set; }
	    public string? reservationnotes1 { get; set; }
	    public string? reservationnotes2 { get; set; }
	    public string? scpwdmethod { get; set; }
	    public decimal? n_of_pax { get; set; }
        public decimal? n_of_senior { get; set; }
        public string? pos_customer { get; set; }
        public string? pos_tin {  get; set; }
	    public string? pos_address { get; set; }
        public string? pos_business { get; set; }
	    public decimal? VATable_sales { get; set; }
        public decimal? VAT_amount { get; set; }
	    public decimal? VAT_exempt {  get; set; }
	    public decimal? zero_rated { get; set; }
        public string? GTransactionno {  get; set; }
	    public string? VoidTransactionNo {  get; set; }
	    public string? VoidGTransactionno { get; set; }
        public string? billingtrno { get; set; }
        public string? billingcode { get; set; }
        public decimal? ccpay { get; set; }
        public DateTime? timein { get; set; }
        public DateTime? timeout { get; set; }
        public string? deliveredby { get; set; }
        public string? deliveryContact { get; set; }
        public string? printername { get; set; }
        public string? suppliername { get; set; }
	    public string? accesstoken { get; set; }
        public string? partnerkey { get; set; }
        public string? void_referencenumber { get; set; }
    }
    
}
